language: r
cache: packages
after_success:
  - Rscript -e 'library(covr); codecov()'
matrix:
  include:
    - os: linux
      r: oldrel
      dist: trusty
      warnings_are_errors: true
      sudo: required
      fortran: false
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: linux
      r: release
      dist: trusty
      warnings_are_errors: true
      sudo: required
      fortran: false
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: linux
      r: devel
      dist: trusty
      warnings_are_errors: true
      sudo: required
      fortran: false
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: linux
      r: oldrel
      dist: trusty
      warnings_are_errors: true
      sudo: required
      fortran: false
      osx_image: xcode9
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: linux
      r: release
      dist: trusty
      warnings_are_errors: true
      sudo: required
      fortran: false
      osx_image: xcode9
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE


